apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service-001
  description: First service for backstage demo
  tags:
    - dotnet
    - data
  links:
    - url: https://github.com/borixcr/demo-service-001
      title: Source Code
      icon: github
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: borixcr
  dependsOn:
    - resource:'demo-database'
    - component:'demo-service-002'
    - api:'api-demo-001'
  
  
